<?php 

$bgs=array(""=>"bgDefault",
			"bs"=>"bgBaby",
            "cl"=>"bgCollectibles",
            "cp"=>"bgCleaning",
            "f"=>"bgFlatware",
            "fcs"=>"bgFlatware",
            "g"=>"bgGift",
            "h"=>"bgHollowware",
            "j"=>"bgJewelry",
            "m"=>"bgManufacturer",
            "ps"=>"bgFlatware",	
            "s"=>"bgSearch",
            "sp"=>"bgServingPieces",
            "stp"=>"bgStorage",
            "xm"=>"bgChristmas",
            "cs"=>"bgCoinSilver");
            
$borderClass=array(""=>"bottomBorderDefault",
					"bs"=>"bottomBorderBlue",
                    "cl"=>"bottomBorderTan",
                    "cp"=>"bottomBorderRed",
                    "cs"=>"bottomBorderTan",
                    "f"=>"bottomBorderTan",
                    "fcs"=>"bottomBorderTan",
                    "g"=>"bottomBorderBlue",
                    "h"=>"bottomBorderRed",
                    "j"=>"bottomBorderBlue",
                    "m"=>"bottomBorderTan",
                    "ps"=>"bottomBorderTan",
                    "sp"=>"bottomBorderTan",
                    "stp"=>"bottomBorderRed",
                    "xm"=>"bottomBorderGreen");
                    
                    
$brandContainerIDs=array("bs"=>"babySilverBrandContainer",
						"cl"=>"collectiblesBrandContainer",
						"cs"=>"coinSilverBrandContainer",
						"f"=>"flatwareBrandContainer",
						"h"=>"hollowwareBrandContainer",
						"j"=>"jewelryBrandContainer");
						
						                 
$cats=array(
			'' =>'Silver',
			'cs'=>'Coin Silver',
			'sp'=>'Serving Pieces',
			'fcs'=>'Complete Sets',
			'f'=>'Flatware',
			'ps'=>'Place Settings',
			'h'=>'Hollowware',
			'bs'=>'Baby Silver',
			'j'=>'Jewelry');      
			            
$catLinksIDs=array(
					""	=>"defaultCatLinks",
					"bs"=>"babyCatLinks",
                    "cp"=>"cleaningCatLinks",
                    "cl"=>"collectiblesCatLinks",
                    "cs"=>"coinSilverCatLinks",
                    "f"	=>"flatwareCatLinks",
                    "fcs"=>"flatwareCatLinks",
                    "g"=>"giftCatLinks",
                    "h"=>"hollowwareCatLinks",
                    "j"=>"jewelryCatLinks",
                    "ps"=>"flatwareCatLinks",
                    "sp"=>"servingCatLinks",
                    "stp"=>"storageCatLinks",
                    "xm"=>"christmasCatLinks");

$catSubFolders=array("Silver"=>"silver",
    				"Baby Silver"=>"baby-silver",
    				"Christmas"=>"christmas",
    				"Coin Silver"=>"coin-silver",
    				"Collectibles"=>"silver-collectibles",
    				"Flatware"=>"silver-flatware",
    				"Hollowware"=>"silver-hollowware",
    				"Jewelry"=>"silver-jewelry",
    				"Serving Pieces"=>"silver-serving-pieces",
    				"Silver Care"=>"silver-care",
    				"Silver Storage"=>"silver-storage");

$h1ContainerIDs=array(""=>"defaultH1Container",
						"bs"=>"babyH1Container",
                        "cp"=>"cleaningH1Container",
                        "cl"=>"collectiblesH1Container",
                        "cs"=>"coinSilverH1Container",
                        "f"=>"flatwareH1Container",
                        "fcs"=>"flatwareH1Container",
                        "g"=>"giftH1Container",
                        "h"=>"hollowwareH1Container",
                        "j"=>"jewelryH1Container",
                        "ps"=>"flatwareH1Container",
                        "stp"=>"storageH1Container",
                        "sp"=>"servingH1Container",
                        "xm"=>"christmasH1Container");

$h1IDs=array(""=>"defaultH1",
				"bs"=>"babySilverH1",
                "cp"=>"cleaningH1",
                "cl"=>"collectiblesH1",
                "cs"=>"coinSilverH1",
                "f"=>"flatwareH1",
                "fcs"=>"flatwareH1",
                "g"=>"giftH1",
                "h"=>"hollowwareH1",
                "j"=>"jewelryH1",
                "ps"=>"flatwareH1",
                "stp"=>"storageH1",
                "sp"=>"servingH1",
                "xm"=>"christmasH1");

$h2ID=array(""=>"defaultH2",
				"bs"=>"babyH2",
                "cp"=>"cleaningH2",
                "cl"=>"collectiblesH2",
                "cs"=>"coinSilverH2",
                "f"=>"flatwareH2",
                "fcs"=>"flatwareH2",
                "g"=>"giftH2",
                "h"=>"hollowwareH2",
                "j"=>"jewelryH2",
                "ps"=>"flatwareH2",
                "stp"=>"storageH2",
                "sp"=>"servingH2",
                "xm"=>"christmasH2");

$homePage=array("f"=>"/silver-flatware/",
				"fcs"=>"/silver-flatware/",
                "h"=>"/silver-hollowware/",
                "j"=>"/silver-jewelry/",
                "bs"=>"/baby-silver/",
                "cl"=>"/silver-collectibles/",
                "cs"=>"/coin-silver/",
                "ps"=>"/silver-flatware/",
                "r"=>"/repairs.php",
                "g"=>"/giftRegistry.php",
                "sp"=>"/silver-flatware/",
                "xm"=>"/productSearch.php?category=xm");

$keyCat=array(''=>'Silver',
                'sp'=>'Serving Pieces',
                'ps'=>'Flatware',
                'fcs'=>'Complete Sets',
                'f'=>'Flatware',
                'h'=>'Hollowware',
                'bs'=>'Baby Silver',
                'j'=>"Jewelry",
                'cp'=>'Silver Care',
                'cs'=>'Coin Silver',
                'stp'=>'Silver Storage',
                'xm'=>'Christmas',
                'cl'=>'Collectibles');
                
$keywordCats=array(
				"" => "Silver",
				"Silver"=>"Flatware, Hollowware, Serving Pieces",
                "Serving Pieces"=>"Serving Pieces",
                "Flatware"=>"Flatware, Place Settings, Serving Pieces",
                "Complete Sets"=>"Complete Sets,Flatware, Place Settings",
                "Hollowware"=>"Hollowware",
                "Baby Silver"=>"Baby Silver",
                "Jewelry"=>"Jewelry",
                "Silver Care"=>"Silver Care Products",
                "Silver Storage"=>"Silver Storage Products",
                "Christmas"=>"Christmas",
                "Collectibles"=>"Collectibles",
                "Coin Silver"=>"Coin Silver"
                );

$liClass=array(""=>"defaultDropdownLI",
				"bs"=>"babyDropdownLI",
                "cl"=>"collectiblesDropdownLI",
                "cp"=>"cleaningDropdownLI",
                "cs"=>"coinSilverDropdownLI",
                "f"=>"flatwareDropdownLI",
                "fcs"=>"flatwareDropdownLI",
                "g"=>"giftDropdownLI",
                "h"=>"hollowwareDropddownLI",
                "j"=>"jewelryDropdownLI",
                "ps"=>"flatwareDropdownLI",
                "r"=>"repairsDropdownLI",
                "sp"=>"flatwareDropdownLI");

$mainContentHeaderImages=array(""=>"defaultImage",
								"bs"=>"babySilverImage",
                                "cp"=>"cleaningImage",
                                "cl"=>"collectiblesImage",
                                "cs"=>"coinSilverImage",
                                "f"=>"flatwareImage",
                                "fcs"=>"flatwareImage",
                                "g"=>"giftImage",
                                "h"=>"hollowwareImage",
                                "j"=>"jewelryImage",
                                "ps"=>"flatwareImage",
                                "sp"=>"servingImage",
                                "stp"=>"cleaningImage",
                                "xm"=>"christmasImage");

$mobilePageHeads=array(
					""=>"defaultMobileHead",
					"bs"=>"blueMobileHead",
					"cl"=>"tanMobileHead",
					"cp"=>"defaultMobileHead",
					"h"=>"defaultMobileHead",
					"f"=>"tanMobileHead",
					"fcs"=>"tanMobileHead",
					"j"=>"blueMobileHead",
					"sp"=>"tanMobileHead",
					"xm"=>"greenMobileHead");    
					                            
                                
$onloadCodes=array("bs"=>"bsa");

$pageHeadImages=array(''=>'r',
						'f'=>'t',
                        'fcs'=>'t',
                        'g'=>'b',
                        'cl'=>'t',
                        'cs'=>'t',
                        'h'=>'r',
                        'bs'=>'b',
                        'j'=>'b',
                        'cp'=>'r',
                        'ps'=>'t',
                        'sp'=>'t',
                        'stp'=>'r',
                        'xm'=>'g');

$pageHeadIDs=array(""=>"defaultPageHead",
					"bs"=>"babySilverPageHead",
                    "cp"=>"cleaningPageHead",
                    "cl"=>"collectiblesPageHead",
                    "cs"=>"coinSilverPageHead",
                    "f"=>"flatwarePageHead",
                    "fcs"=>"flatwarePageHead",
                    "g"=>"giftPageHead",
                    "h"=>"hollowwarePageHead",
                    "j"=>"jewelryPageHead",
                    "ps"=>"flatwarePageHead",
                    "sp"=>"servingPageHead",
                    "stp"=>"cleaningPageHead",
                    "xm"=>"christmasPageHead");

$pageHeadImageIDs=array(""=>"defaultHead",
						"bs"=>"babySilverHead",
                        "cp"=>"cleaningHead",
                        "cl"=>"collectiblesHead",
                        "cs"=>"coinSilverPageHead",
                        "f"=>"flatwareHead",
                        "fcs"=>"flatwareHead",
                        "g"=>"giftHead",
                        "h"=>"hollowwareHead",
                        "j"=>"jewelryHead",
                        "ps"=>"flatwareHead",
                        "sp"=>"servingHead",
                        "stp"=>"storageHead",
                        "xm"=>"christmasHead");

$sideMenus=array("bs"=>"bsMenu.inc",
                 "cl"=>"clMenu.inc",
                 "cs"=>"csMenu.inc",
                 "f"=>"fMenu.inc",
                 "h"=>"hMenu.inc",
                "j"=>"jMenu.inc");

$sideMenuIDs=array("bs"=>"babySideMenu",
					"cl"=>"collectiblesSideMenu",
					"cs"=>"coinSilverSideMenu",
					"f"=>"flatwareSideMenu",
					"fcs"=>"flatwareSideMenu",
					"g"=>"giftSideMenu",
					"h"=>"hollowwareSideMenu",
					"j"=>"jewelrySideMenu",
					"sp"=>"servingPiecesSideMenu",
					"stp"=>"storageSideMenu",
					"xm"=>"christmasSideMenu");
					
$sideMenuLinks=array("bs"=>"babySideMenuLink",
					"cl"=>"collectiblesSideMenuLink",
					"cs"=>"coinSilverSideMenuLink",
					"f"=>"flatwareSideMenuLink",
					"fcs"=>"flatwareSideMenuLink",
					"g"=>"giftSideMenuLink",
					"h"=>"hollowwareSideMenuLink",
					"j"=>"jewelrySideMenuLink",
					"sp"=>"flatwareSideMenuLink",
					"stp"=>"storageSideMenuLink",
					"xm"=>"christmasSideMenuLink");
					
$staticcats=array(""=>"All",
				"sp"=>'Flatware',
                "fcs"=>'Flatware',
                "f"=>'Flatware',
                "g"=>'Gifts',
                "ps"=>'Flatware',
                "h"=>'Hollowware',
                "bs"=>'Baby Silver',
                "j"=>'Jewelry',
                "stp"=>'SilverStorage',
                "cp"=>'SilverCare',
                "xm"=>'Christmas',
                "cl"=>'Collectibles',
                "cs"=>'Coin Silver');

$style=array(''=>'',
			'f'=>'_tan',
            'fcs'=>'_tan',
            'g'=>'_blue',
            'cl'=>'_tan',
            'cs'=>'_tan',
            'h'=>'',
            'bs'=>'_blue',
            'j'=>'_jewelry',
            'cp'=>'',
            'ps'=>'_tan',
            'sp'=>'_tan',
            'stp'=>'',
            'c'=>'',
            'xm'=>'_christmas');

$template=array("bs"=>"bs",
                "cl"=>"f",
                "cl"=>"f",
                "f"=>"f",
                "fcs"=>"f",
                "g"=>"g",
                "h"=>"h",
                "j"=>"j",
                "m"=>"f",
                "ps"=>"f",
                "s"=>"h",
                "sp"=>"f",
                "xm"=>"xm");
                
$titles=array("f"=>"t_flat_main_alt.jpg\" title=\"<!pattern> Silver Flatware\" alt=\"<!pattern>  Silver Flatware\"",
			"h"=>"t_hol_main_alt.jpg\" title=\"<!pattern> Silver Hollowware\" alt=\"<!pattern> Silver Hollowware\"",
			"bs"=>"t_baby_main_alt.jpg\" title=\"<!pattern> Baby Silver\" alt=\"<!pattern>  Baby Silver\"",
			"j"=>"t_jew_main_alt.jpg\" title=\"<!pattern> Silver Jewelry\" alt=\"<!pattern> Silver Jewelry\"",
			"cp"=>"t_caring.jpg\" title=\"<!pattern> Silver Cleaning Products\" alt=\"<!pattern> Silver Cleaning Products\"",
			"stp"=>"t_caring.jpg\" title=\"<!pattern> Silver Storage Products\" alt=\"<!pattern> Silver Storage Products\"",
			"xm"=>"t_xmas_main_alt.jpg\" title=\"<!pattern> Silver Christmas Ornaments\" alt=\"<!pattern> Silver Christmas Ornaments\"",
			"cl"=>"t_collectibles_alt.jpg\" title=\"<!pattern> Silver Collectibles\" alt=\"<!pattern> Silver Collectibles\"",
			"cs"=>"t_flat_main_alt.jpg\" title=\"<!pattern> Coin Silver\" alt=\"<!pattern> Coin Silver\"");
?>