<!DOCTYPE html PUBLIC "-/W3C/DTD XHTML 1.0 Transitional/EN" "http:/www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http:/www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<title> As You Like It Silver Shop </title>

<meta name="description" content="As You Like It Silver Shop in New Orleans Louisiana specializes in silver flatware and holloware in active, inactive and obsolete patterns." />

<meta name="keywords" content="sterling silver, sterling flatware, silver flatware, antique silver, silver tableware, antique sterling, replacement silver, silver repair, corporate gifts, wedding gifts, silver identification, cleaning silver" />
<script language="javascript" src='/js/images.js'></script>
<script language='javascript' src='/js/store.js'></script>
<link rel="stylesheet" href="/ayliss_style_blue.css" type="text/css">
<link rel="stylesheet" href="/ayliss_style_uni.css" type="text/css">

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31581272-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

</head>

<body class="sub" onLoad=preLoad('bsa')>

<div id="container">
<div class="pageHead" id="babySilverPageHead">
 <div id="cartContainer">
  <p class="homenav">
   YOUR SILVER CHEST HAS 
   <img src='/images/c__.gif' name=nums3 align=bottom>
   <img src='/images/c__.gif' name=nums2 align=bottom>
   <img src='/images/c_0.gif' name=nums1 align=bottom> ITEMS.
   <a href="/orderdetails.php" class="top">
     <img class="silverChest" src="/images/silverchest_empty.gif" name=chest>
   </a>
  </p>
 </div>

 <div id="babySilverHead">
   <img src="/images/ayliss_title_b.jpg" alt="Sterling Baby Silver at As You Like It Silver Shop in New Orleans" title="Sterling Baby Silver at As You Like It Silver Shop in New Orleans">
  </div>  


