brands['any']=new Array('');
brands['all']=new Array("CHRISTOFLE","DURGIN","GORHAM","HOLMES & EDWARDS","INTERNATIONAL","REED & BARTON","TOWLE","WALLACE")

brands["1810"]=new Array('INTERNATIONAL')

brands["BURGUNDY"]=new Array('REED & BARTON')

brands["CHANTILLY"]=new Array('GORHAM')

brands["FAIRFAX"]=new Array('GORHAM')

brands["GRANDE BAROQUE"]=new Array('WALLACE')

brands["KING RICHARD"]=new Array('TOWLE')

brands["MEDICI"]=new Array('GORHAM')

brands["NEW VINTAGE"]=new Array('DURGIN')

brands["RENAISSANCE"]=new Array('CHRISTOFLE')

brands["ROSEPOINT"]=new Array('WALLACE')

brands["ROYAL DANISH"]=new Array('INTERNATIONAL')

brands["YOUTH"]=new Array('HOLMES & EDWARDS')
