brands['any']=new Array('');
brands['all']=new Array('CHRISTOFLE','FRANK SMITH','GORHAM','INTERNATIONAL','REED & BARTON','TOWLE','WALLACE')

brands["CHANTILLY"] = new Array('GORHAM')

brands["FAIRFAX"] = new Array('GORHAM')

brands["FIDDLE THREAD"] = new Array('FRANK SMITH')

brands["FRANCIS I"] = new Array('REED & BARTON')

brands["KING RICHARD"] = new Array('TOWLE')

brands["MEDICI"] = new Array('GORHAM')

brands["OLD MASTER"] = new Array('TOWLE')

brands["RENAISSANCE"] = new Array('CHRISTOFLE')

brands["ROSEPOINT"] = new Array('WALLACE')

brands["ROYAL DANISH"] = new Array('INTERNATIONAL')

brands["TIGER LILY"] = new Array('REED & BARTON')
