brands['any']=new Array('');
brands['all']=new Array("ALBERT COLES","ALVIN","BLACKINTON","CHRISTOFLE","Cort Hannibal","DOMINICK & HAFF","DURGIN","DURGIN - GORHAM","E. H. H. SMITH SILVER CO.","EMILE PUIFORCAT","FABERGE","FRANK M. WHITING","FRANK SMITH","GEORG JENSEN","GORHAM","HANS HANSEN","HARRISON BROS. & HOWSON","HOTCHKISS & SCHREUDER","HYDE & GOODRICH","INTERNATIONAL","J. DUNCAN","JEAN-BAPTISTE-DENIS LANDRY","JOHN POLHAMUS","JOSEPH SEYMOUR","KIRK","KNOWLES","KRIDER & BIDDLE","LANDERS, FRARY & CLARK","LIONEL ALFRED CRICHTON","LUNT","MAGNUS AASE","OLD NEWBURY CRAFTERS","ONEIDA","PARODI","PAYE & BAKER","REED & BARTON","RICHARD BRITTON","SAMUEL HAYNE & DUDLEY CATER","Samuel Hildeburn","SCHOFIELD","SHIEBLER","SHREVE","STIEFF","THOMAS FARNELL","TIFFANY","TOWLE","TURNER & SIMPSON","UNGER BROTHERS","UNKNOWN","UNKNOWN MAKER","WALLACE","WATSON","WEBSTER COMPANY","WENDT","WHITING","WILLIAM CHAWNER II","WOOD & HUGHES")

brands["No Pattern"]=new Array('ALBERT COLES','Cort Hannibal','DOMINICK & HAFF','EMILE PUIFORCAT','FRANK M. WHITING','GEORG JENSEN','GORHAM','HANS HANSEN','HARRISON BROS. & HOWSON','HOTCHKISS & SCHREUDER','HYDE & GOODRICH','J. DUNCAN','KIRK','KRIDER & BIDDLE','LANDERS, FRARY & CLARK','MAGNUS AASE','PARODI','RICHARD BRITTON','SAMUEL HAYNE & DUDLEY CATER','Samuel Hildeburn','THOMAS FARNELL','TIFFANY','TOWLE','TURNER & SIMPSON','UNKNOWN','WALLACE','WATSON','WEBSTER COMPANY','WHITING','WILLIAM CHAWNER II')

brands["1810"]=new Array('INTERNATIONAL')

brands["ABBOTTSFORD"]=new Array('INTERNATIONAL')

brands["ACORN"]=new Array('GEORG JENSEN')

brands["ALHAMBRA"]=new Array('WHITING')

brands["AMARYLLIS"]=new Array('REED & BARTON')

brands["ANGELO"]=new Array('WOOD & HUGHES')

brands["ANTIQUE LILY ENGRAVED"]=new Array('WHITING')

brands["ARABESQUE"]=new Array('WHITING')

brands["BALTIMORE ROSE"]=new Array('SCHOFIELD')

brands["BARONIAL, OLD"]=new Array('GORHAM')

brands["BEAD"]=new Array('WHITING')

brands["BIRD"]=new Array('WENDT')

brands["BRIDAL ROSE"]=new Array('ALVIN')

brands["BURGUNDY"]=new Array('REED & BARTON')

brands["BUTTERCUP"]=new Array('GORHAM')

brands["CAMBRIDGE"]=new Array('GORHAM')

brands["CAMELLIA"]=new Array('GORHAM')

brands["CANTERBURY"]=new Array('TOWLE')

brands["CARNATION"]=new Array('WALLACE')

brands["CHANTILLY"]=new Array('GORHAM')

brands["CHATEAU ROSE"]=new Array('ALVIN')

brands["CHRYSANTHEMUM"]=new Array('DURGIN','STIEFF','TIFFANY')

brands["CLOETA"]=new Array('INTERNATIONAL')

brands["CLUNY"]=new Array('GORHAM')

brands["COLFAX"]=new Array('DURGIN','GORHAM')

brands["CONTRAST"]=new Array('LUNT')

brands["CORINTHIAN"]=new Array('GORHAM','JOHN POLHAMUS')

brands["CUPID"]=new Array('SHIEBLER')

brands["DAISY"]=new Array('BLACKINTON','PAYE & BAKER')

brands["DANCING SURF"]=new Array('KIRK')

brands["DAUPHIN"]=new Array('DURGIN - GORHAM')

brands["DEBUSSY"]=new Array('TOWLE')

brands["DELLA ROBBIA"]=new Array('ALVIN')

brands["DIAMOND"]=new Array('JOHN POLHAMUS')

brands["DU BARRY"]=new Array('DURGIN','INTERNATIONAL')

brands["DUKE OF YORK"]=new Array('WHITING')

brands["EIGHTEENTH CENTURY"]=new Array('REED & BARTON')

brands["EL GRANDEE"]=new Array('TOWLE')

brands["ELOQUENCE"]=new Array('LUNT')

brands["EMPIRE"]=new Array('WHITING')

brands["ENGLISH CHIPPENDALE"]=new Array('REED & BARTON')

brands["ENGLISH KING"]=new Array('TIFFANY')

brands["ETON"]=new Array('WALLACE')

brands["ETRUSCAN"]=new Array('GORHAM')

brands["FAIRFAX"]=new Array('GORHAM')

brands["FIDDLE BACK"]=new Array('THOMAS FARNELL','UNKNOWN')

brands["FIDDLE THREAD"]=new Array('FRANK SMITH','GORHAM','JEAN-BAPTISTE-DENIS LANDRY','UNKNOWN')

brands["FIRST LOVE"]=new Array('ONEIDA')

brands["FLORA"]=new Array('SHIEBLER')

brands["FLORENTINE"]=new Array('GORHAM')

brands["FONTAINEBLEAU"]=new Array('GORHAM')

brands["FOURTEENTH CENTURY"]=new Array('SHREVE')

brands["FRANCIS I"]=new Array('REED & BARTON')

brands["FRANCIS I (OLD HALLMARKS)"]=new Array('REED & BARTON')

brands["FRENCH RENAISSANCE"]=new Array('REED & BARTON')

brands["FRONTENAC"]=new Array('INTERNATIONAL')

brands["GATCHINA PALACE"]=new Array('FABERGE')

brands["GEORGIAN"]=new Array('TOWLE')

brands["GRAND EUROPA"]=new Array('FABERGE')

brands["GRANDE BAROQUE"]=new Array('WALLACE')

brands["GRANDE RENAISSANCE"]=new Array('REED & BARTON')

brands["H239"]=new Array('GORHAM')

brands["HARLEQUIN"]=new Array('REED & BARTON')

brands["HENRY II"]=new Array('GORHAM')

brands["HERALDIC"]=new Array('DURGIN','WHITING')

brands["HIZEN"]=new Array('GORHAM')

brands["HOLLY"]=new Array('E. H. H. SMITH SILVER CO.')

brands["HONEYSUCKLE"]=new Array('WHITING')

brands["IMPERIAL CHRYSANTHEMUM"]=new Array('GORHAM')

brands["IMPERIAL COURT"]=new Array('FABERGE')

brands["IMPERIAL QUEEN"]=new Array('WHITING')

brands["IMPERO"]=new Array('WALLACE')

brands["IRIS"]=new Array('DURGIN')

brands["ITALIAN J"]=new Array('WHITING')

brands["JAPANESE"]=new Array('WENDT')

brands["JEANNE D\'ARC"]=new Array('INTERNATIONAL')

brands["JOAN OF ARC"]=new Array('INTERNATIONAL')

brands["KING"]=new Array('KIRK')

brands["KING GEORGE"]=new Array('GORHAM')

brands["KING RICHARD"]=new Array('TOWLE')

brands["KINGS"]=new Array('UNKNOWN MAKER')

brands["LA REINE"]=new Array('WALLACE')

brands["LA SCALA"]=new Array('GORHAM')

brands["LABORS OF CUPID"]=new Array('DOMINICK & HAFF')

brands["LANCASTER"]=new Array('GORHAM')

brands["LANSDOWNE"]=new Array('GORHAM')

brands["LES CINQ FLEURS"]=new Array('REED & BARTON')

brands["LILY"]=new Array('WATSON','WHITING')

brands["LILY OF THE VALLEY"]=new Array('WHITING')

brands["LOUIS XIV"]=new Array('TOWLE')

brands["LOUIS XV"]=new Array('WHITING')

brands["LUCERNE"]=new Array('WALLACE')

brands["LUXEMBOURG"]=new Array('GORHAM','SHIEBLER')

brands["MARIE ANTOINETTE"]=new Array('GORHAM')

brands["MARLBOROUGH"]=new Array('REED & BARTON')

brands["MAYFLOWER"]=new Array('KIRK')

brands["MEDICI, OLD"]=new Array('GORHAM')

brands["MELROSE"]=new Array('GORHAM')

brands["MODERN VICTORIAN"]=new Array('LUNT')

brands["MONTEREY"]=new Array('ALVIN')

brands["MONTICELLO"]=new Array('LUNT')

brands["MYTHOLOGIQUE"]=new Array('GORHAM')

brands["NARCISSUS"]=new Array('UNGER BROTHERS')

brands["NELLIE CUSTIS"]=new Array('LUNT')

brands["NEW KING"]=new Array('DOMINICK & HAFF')

brands["NEW QUEENS"]=new Array('GORHAM')

brands["NEW VINTAGE"]=new Array('DURGIN')

brands["NO 1"]=new Array('WHITING')

brands["NO 14C"]=new Array('GORHAM')

brands["NO 38 ENGRAVED"]=new Array('TOWLE')

brands["NO 80"]=new Array('WALLACE')

brands["NO. 39"]=new Array('WHITING')

brands["NOCTURNE"]=new Array('GORHAM')

brands["NUREMBURG"]=new Array('ALVIN')

brands["OAK LEAF"]=new Array('OLD NEWBURY CRAFTERS')

brands["OLD ATLANTA (IRVING)"]=new Array('WALLACE')

brands["OLD COLONIAL"]=new Array('TOWLE')

brands["OLD COLONY, OLD"]=new Array('GORHAM')

brands["OLD ENGLISH TIPT"]=new Array('GORHAM')

brands["OLD FRENCH"]=new Array('GORHAM')

brands["OLD MARYLAND"]=new Array('KIRK')

brands["OLD MARYLAND ENGRAVED"]=new Array('KIRK')

brands["OLD MASTER"]=new Array('TOWLE')

brands["OLD NEWBURY"]=new Array('TOWLE')

brands["OLYMPIAN"]=new Array('TIFFANY')

brands["ORANGE BLOSSOM"]=new Array('DURGIN')

brands["OVAL TWIST"]=new Array('WHITING')

brands["PADOVA"]=new Array('TIFFANY')

brands["PAUL REVERE"]=new Array('TOWLE')

brands["PERSIAN"]=new Array('TIFFANY')

brands["PLYMOUTH"]=new Array('GORHAM')

brands["POINTED ANTIQUE"]=new Array('REED & BARTON')

brands["POMONA"]=new Array('TOWLE')

brands["POMPADOUR"]=new Array('WHITING')

brands["POPPY"]=new Array('GORHAM')

brands["PRELUDE"]=new Array('INTERNATIONAL')

brands["PRINCESS"]=new Array('TOWLE')

brands["PROVENCE"]=new Array('TIFFANY')

brands["PYRAMID"]=new Array('GEORG JENSEN')

brands["QUEEN ELIZABETH"]=new Array('TOWLE')

brands["QUEENS"]=new Array('WALLACE')

brands["RATTAIL"]=new Array('LIONEL ALFRED CRICHTON')

brands["RENAISSANCE"]=new Array('DOMINICK & HAFF')

brands["REPOUSSE"]=new Array('KIRK')

brands["RICHELIEU"]=new Array('INTERNATIONAL','TIFFANY')

brands["ROCOCO"]=new Array('DOMINICK & HAFF')

brands["ROMAINE"]=new Array('REED & BARTON')

brands["ROMANCE OF THE SEA"]=new Array('WALLACE')

brands["ROSE"]=new Array('KNOWLES','WALLACE')

brands["ROSE ENGRAVED"]=new Array('JOSEPH SEYMOUR')

brands["ROSEPOINT"]=new Array('WALLACE')

brands["ROSETTE"]=new Array('WHITING')

brands["ROYAL DANISH"]=new Array('INTERNATIONAL')

brands["ROYAL HUSK"]=new Array('WALLACE')

brands["ROYAL ROSE"]=new Array('WALLACE')

brands["RUSTIC"]=new Array('TOWLE')

brands["SCROLL"]=new Array('GEORG JENSEN')

brands["SECRET GARDEN"]=new Array('GORHAM')

brands["SIR CHRISTOPHER"]=new Array('WALLACE')

brands["SPANISH BAROQUE"]=new Array('REED & BARTON')

brands["SPATOURS"]=new Array('CHRISTOFLE')

brands["ST CLOUD"]=new Array('GORHAM')

brands["STIEFF ROSE"]=new Array('STIEFF')

brands["STRASBOURG"]=new Array('GORHAM')

brands["STRATFORD"]=new Array('INTERNATIONAL')

brands["THESEUM"]=new Array('INTERNATIONAL')

brands["TRIANON"]=new Array('INTERNATIONAL')

brands["TYROLEAN"]=new Array('FRANK M. WHITING')

brands["VERSAILLES"]=new Array('GORHAM')

brands["VIKING"]=new Array('ALVIN')

brands["VINE"]=new Array('TIFFANY')

brands["VIOLET"]=new Array('WALLACE','WHITING')

brands["VIRGINIANA"]=new Array('GORHAM')

brands["WARWICK"]=new Array('INTERNATIONAL')

brands["WASHINGTON"]=new Array('WALLACE')

brands["WATTEAU"]=new Array('DURGIN','WATSON')

brands["WEDGEWOOD"]=new Array('INTERNATIONAL')

brands["WILD ROSE"]=new Array('INTERNATIONAL')

brands["WILLIAM & MARY"]=new Array('LUNT')

brands["WINSLOW"]=new Array('KIRK')
