<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/ring/submit/Display" class=listme>Rings</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/cuff%2Blink/submit/Display" class=listme>Cuff Links</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/earring/submit/Display" class=listme>Earrings</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/necklace%20pendant/submit/Display" class=listme>Necklaces and Pendants</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/pin%20/submit/Display" class=listme>Pins</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/charm%20watch%20/submit/Display" class=listme>Miscellaneous</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/bracelet/submit/Display" class=listme>Bracelets</a>
<li>  <a href="/showSearch/category/j,h/template/j/brand//pattern//item/pendant/submit/Display" class=listme>test</a>
